resourcePrefix: sls-template-repo
lambdaVersionsToKeep: 5
logLevel: DEBUG
logRetentionInDays: 30
assumedRoleArn: arn:aws:iam::023800413984:role/serverless-template-repo-DeployerRole
deploymentRoleArn: arn:aws:iam::023800413984:role/serverless-template-repo-CloudFormationExecutionRole
permissionBoundaryArn: # Removed During PoC - Needs to be added back in before deployment to Dev/Stg/Prd

# Options for Data Dog
# datadogSite: datadoghq.eu
# nableDatadog: true
# datadogApiKeyArn: # arn:aws:secretsmanager:eu-west-1:XXXXXXXXXX:secret:DdApiKeySecret-RuKpCqDVnRu0-Hls2wA

# Options for Private API Gateway
apiGatewayArn: # arn:aws:execute-api:eu-west-1:XXXXXXXXXX
vpcId: # vpc-XXXXXXXXXX
vpcEndpointId: # vpce-XXXXXXXXXX

# Options for DynamoDB
dynamoReadCapacity: # 2
dynamoWriteCapacity: # 1

# Options for S3
s3Bucket: # arn:aws:s3:::elemica-<service-name>-<environment>

# Options for SQS / SNS
inTopicEndpoint: # arn:aws:sns:eu-west-1:XXXXXXXXXX:sns-for-ses-<service-name>-<environment>
outTopicEndpoint: # arn:aws:sns:eu-west-1:XXXXXXXXXX:sns-for-sqs-<service-name>-<environment>
